apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.carSimulator.name }}
  annotations:
    haproxy.router.openshift.io/timeout: 10000ms
  name: {{ .Values.carSimulator.name }}
spec:
  port:
    targetPort: 8080-tcp
  {{- if .Values.tls.enabled }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.carSimulator.name }}
    weight: 100
  wildcardPolicy: None
