apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: kafka2datagrid
  labels:
    app.kubernetes.io/part-of: {{ .Values.appName }}
spec:
  configuration:
    - type: secret
      value: kafka2datagrid
  profile: OpenShift
  sources:
    - content: {{ .Files.Get "data/java/KafkaToDatagridRoute.java" | quote }}
      name: KafkaToDatagridRoute.java
  traits:
    service:
      configuration:
        enabled: false