kind: Secret
apiVersion: v1
metadata:
  name: kafka2datagrid
stringData:
  application.properties: |-
    com.redhat.bobbycar.camelk.dg.car.snapshot.cacheName={{ .Values.datagrid.cache.snapshot }}
    com.redhat.bobbycar.camelk.dg.car.cacheName={{ .Values.datagrid.cache.car }}
    com.redhat.bobbycar.camelk.dg.zone.cacheName={{ .Values.datagrid.cache.zone }}
    com.redhat.bobbycar.camelk.dg.refresh.interval={{ .Values.datagrid.cache.refresh.interval }}
    com.redhat.bobbycar.camelk.dg.host=bobbycar-dg
    com.redhat.bobbycar.camelk.dg.password={{ .Values.datagrid.account.password }}
    com.redhat.bobbycar.camelk.dg.user={{ .Values.datagrid.account.user }}
    com.redhat.bobbycar.camelk.kafka.brokers={{ .Values.kafka.bootstrap.servers }}
    com.redhat.bobbycar.camelk.kafka.topic={{ .Values.kafka.topic.drogueEvents }}
    com.redhat.bobbycar.camelk.kafka.topicZoneChange={{ .Values.kafka.topic.zonechange }}
    com.redhat.bobbycar.camelk.dg.ocp.api={{ .Values.ocpApi }}
    com.redhat.bobbycar.camelk.dg.namespace={{ .Values.namespace }}
    camel.component.kafka.securityProtocol=SASL_PLAINTEXT
    camel.component.kafka.saslMechanism=SCRAM-SHA-512
    camel.component.kafka.saslJaasConfig=${KAFKA_JAAS_CONFIG}
    com.redhat.bobbycar.camelk.drogue.endpoint=https://command-endpoint:443
    com.redhat.bobbycar.camelk.drogue.application={{ .Values.drogue.application }}
    com.redhat.bobbycar.camelk.drogue.user=${DROGUE_USER}
    com.redhat.bobbycar.camelk.drogue.token=${DROGUE_ACCESS_TOKEN}
type: Opaque
