apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.kafka.topic.gps.name }}
  namespace: {{ .Values.namespace }}
  labels:
    strimzi.io/cluster: drogue-iot
spec:
  partitions: {{ .Values.kafka.topic.gps.partitions }}
  replicas: {{ .Values.kafka.topic.gps.replicas }}
  config:
    retention.ms: {{ .Values.kafka.topic.gps.retention }}
    segment.bytes: 1073741824
 
