---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: zone-change-kafka-source
  namespace: {{ .Values.namespace }}
spec:
  bootstrapServers:
    - {{ .Values.kafka.bootstrap.servers | quote }}
  consumerGroup: KnativeZoneChangeSource
  net:
    sasl:
      enable: true
      password:
        secretKeyRef:
          name: drogue-iot
          key: password
      type:
        secretKeyRef:
          name: zone-change-kafka-source
          key: type
      user:
        secretKeyRef:
          name: zone-change-kafka-source
          key: user
    tls:
      caCert: { }
      cert: { }
      key: { }
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: {{ .Values.broker.name }}
  topics:
    - {{ .Values.kafkaTopic }}
---
apiVersion: v1
kind: Secret
metadata:
  name: zone-change-kafka-source
  namespace: {{ .Values.namespace }}
data:
  user: {{ "drogue-iot" | b64enc }}
  type: {{ "SCRAM-SHA-512" | b64enc }}
