apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: zone-change-faas
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
        #autoscaling.knative.dev/initialScale: "0"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
        - image: quay.io/bobbycar/zone-change-service:1.0-jvm
        #- image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
          env:
            - name: 'quarkus.rest-client.ota-api.url'
              value: {{ .Values.otaServer.url | quote}}