namespace:
appName: Bobbycar
ocpDomain:
ocpApi:

tls:
  enabled: false

kafka:
  topic:
    gps: bobbycar-gps
    metrics: events-bobbycar # depends on .Values.drogue.application
    zonechange: bobbycar-zonechange
    drogueEvents: events-bobbycar # depends on .Values.drogue.application
  bootstrap:
    servers: drogue-iot-kafka-bootstrap:9092

datagrid:
  cache:
    snapshot: carsnapshots
    car: cars
    zone: zones
    refresh:
      interval: 10000
  account:
    user: replaceme
    password: replaceme

dashboard:
  config:
    googleApiKey:
    threeScaleApiKey: replaceme
    hdppEndpoint: http://ntt-stream-hdpp.apps.ocp4.rhlab.de/playlist.m3u8

carSimulator:
  name: car-simulator 
  replicas: 1
  config:
    carsimCars: 20
    carsimFactor: 3
    carsimRepeat: true
    carsimDelay: 1000

drogue:
  application: bobbycar
  endpoints:
    mqtt:
      # host: <override mqtt endpoint host>
      port: 1883
  gateway:
    name: car-gw
    password: car123456
