namespace:
appName: Bobbycar
ocpDomain:
ocpApi:

mqtt:
  topic:
    mqttZoneChangeTopic: bobbycar/zonechange
    mqttMetricsTopic: bobbycar/enginemetrics

kafka:
  topic:
    gps: bobbycar-gps
    metrics: bobbycar-metrics
    zonechange: bobbycar-zonechange
  bootstrap:
    servers: bobbycar-cluster-kafka-bootstrap:9092

datagrid:
  cache:
    snapshot: carsnapshots
    car: cars
    zone: zones
    refresh:
      interval: 10000
  account:
    user: replaceme
    password: replaceme

dashboard:
  config:
    googleApiKey:
    threeScaleApiKey: replaceme
    hdppEndpoint: https://ntt-stream-hdpp.apps.ocp4.rhlab.de/playlist.m3u8

carSimulator:
  name: car-simulator 
  replicas: 1
  config:
    carsimCars: 20
    carsimFactor: 3
    carsimRepeat: true
    carsimDelay: 1000