{{ if .Values.drogueIoT }}
kind: Secret
apiVersion: v1
metadata:
  name: post-install-auto-create
  labels:
    app.kubernetes.io/name: post-install-auto-create
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: drogue-iot
type: Opaque
data:
  {{ $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "data/auto-create/static/*" }}
  {{ base $path }}: {{ tpl ( $.Files.Get $path ) $currentScope | b64enc | quote }}
  {{- end }}

  {{- range $i, $_  := until (int .Values.carSimulator.config.carsimCars) }}
  {{- $_ := set $ "device" (printf "car-%v" $i) }}
  {{- $_ = set $ "password" "car123456" }}
  "device-{{ . }}.json": {{ tpl ( $.Files.Get "data/auto-create/dynamic/device.json" ) $ | b64enc | quote }}
  {{- end }}
{{ end }}
